import {
  Crown, Star, Shield, Headphones, Zap, Heart, Flag, Bell, Bookmark, User, Users, Key, Lock, Award, Wrench, Settings, Music, Mic, Camera, Theater, Swords, Flame, Eye, Globe, Compass, MapPin, Navigation, Anchor, Rocket, Plane, Car, Bike, Bus, Train, Truck, Sun, Moon, Cloud, Snowflake, Umbrella, Droplet, Wind, TreePine as Tree, Leaf, Mountain, Waves, Coffee, Utensils, Gift, PartyPopper, Sparkles, Trophy, Medal, Target, Crosshair, Hammer, Pickaxe, Cpu, Radio, Tv, Film, Video, Palette, Brush, Pen, FileText, Book, MessageSquare, Phone, Mail, Send, Calendar, Clock, Timer, Lightbulb, Lamp, Megaphone, Volume2, ScanLine, QrCode, Fingerprint, Footprints, Hand
} from "lucide-react";

export const ICON_CATALOG = [
  { name: "Crown", label: "クラウン", Icon: Crown },
  { name: "Star", label: "スター", Icon: Star },
  { name: "Shield", label: "シールド", Icon: Shield },
  { name: "Headphones", label: "ヘッドホン", Icon: Headphones },
  { name: "Zap", label: "稲妻", Icon: Zap },
  { name: "Heart", label: "ハート", Icon: Heart },
  { name: "Flag", label: "フラッグ", Icon: Flag },
  { name: "Bell", label: "ベル", Icon: Bell },
  { name: "Bookmark", label: "ブックマーク", Icon: Bookmark },
  { name: "User", label: "ユーザー", Icon: User },
  { name: "Users", label: "ユーザー群", Icon: Users },
  { name: "Key", label: "キー", Icon: Key },
  { name: "Lock", label: "ロック", Icon: Lock },
  { name: "Award", label: "アワード", Icon: Award },
  { name: "Wrench", label: "レンチ", Icon: Wrench },
  { name: "Settings", label: "設定", Icon: Settings },
  { name: "Music", label: "音楽", Icon: Music },
  { name: "Mic", label: "マイク", Icon: Mic },
  { name: "Camera", label: "カメラ", Icon: Camera },
  { name: "Theater", label: "シアター", Icon: Theater },
  { name: "Swords", label: "ソード", Icon: Swords },
  { name: "Flame", label: "フレイム", Icon: Flame },
  { name: "Eye", label: "アイ", Icon: Eye },
  { name: "Globe", label: "グローブ", Icon: Globe },
  { name: "Compass", label: "コンパス", Icon: Compass },
  { name: "MapPin", label: "マップピン", Icon: MapPin },
  { name: "Navigation", label: "ナビ", Icon: Navigation },
  { name: "Anchor", label: "アンカー", Icon: Anchor },
  { name: "Rocket", label: "ロケット", Icon: Rocket },
  { name: "Plane", label: "プレーン", Icon: Plane },
  { name: "Car", label: "カー", Icon: Car },
  { name: "Bike", label: "バイク", Icon: Bike },
  { name: "Bus", label: "バス", Icon: Bus },
  { name: "Train", label: "トレイン", Icon: Train },
  { name: "Truck", label: "トラック", Icon: Truck },
  { name: "Sun", label: "サン", Icon: Sun },
  { name: "Moon", label: "ムーン", Icon: Moon },
  { name: "Cloud", label: "クラウド", Icon: Cloud },
  { name: "Snowflake", label: "スノーフレイク", Icon: Snowflake },
  { name: "Umbrella", label: "アンブレラ", Icon: Umbrella },
  { name: "Droplet", label: "ドロップ", Icon: Droplet },
  { name: "Wind", label: "ウィンド", Icon: Wind },
  { name: "Tree", label: "ツリー", Icon: Tree },
  { name: "Leaf", label: "リーフ", Icon: Leaf },
  { name: "Mountain", label: "マウンテン", Icon: Mountain },
  { name: "Waves", label: "ウェーブ", Icon: Waves },
  { name: "Coffee", label: "コーヒー", Icon: Coffee },
  { name: "Utensils", label: "食器", Icon: Utensils },
  { name: "Gift", label: "ギフト", Icon: Gift },
  { name: "PartyPopper", label: "ポッパー", Icon: PartyPopper },
  { name: "Sparkles", label: "スパークル", Icon: Sparkles },
  { name: "Trophy", label: "トロフィー", Icon: Trophy },
  { name: "Medal", label: "メダル", Icon: Medal },
  { name: "Target", label: "ターゲット", Icon: Target },
  { name: "Crosshair", label: "クロスヘア", Icon: Crosshair },
  { name: "Hammer", label: "ハンマー", Icon: Hammer },
  { name: "Pickaxe", label: "ピッケル", Icon: Pickaxe },
  { name: "Cpu", label: "CPU", Icon: Cpu },
  { name: "Radio", label: "ラジオ", Icon: Radio },
  { name: "Tv", label: "TV", Icon: Tv },
  { name: "Film", label: "フィルム", Icon: Film },
  { name: "Video", label: "ビデオ", Icon: Video },
  { name: "Palette", label: "パレット", Icon: Palette },
  { name: "Brush", label: "ブラシ", Icon: Brush },
  { name: "Pen", label: "ペン", Icon: Pen },
  { name: "FileText", label: "ファイル", Icon: FileText },
  { name: "Book", label: "ブック", Icon: Book },
  { name: "MessageSquare", label: "メッセージ", Icon: MessageSquare },
  { name: "Phone", label: "電話", Icon: Phone },
  { name: "Mail", label: "メール", Icon: Mail },
  { name: "Send", label: "送信", Icon: Send },
  { name: "Calendar", label: "カレンダー", Icon: Calendar },
  { name: "Clock", label: "時計", Icon: Clock },
  { name: "Timer", label: "タイマー", Icon: Timer },
  { name: "Lightbulb", label: "電球", Icon: Lightbulb },
  { name: "Lamp", label: "ランプ", Icon: Lamp },
  { name: "Megaphone", label: "メガホン", Icon: Megaphone },
  { name: "Volume2", label: "音量", Icon: Volume2 },
  { name: "ScanLine", label: "スキャン", Icon: ScanLine },
  { name: "QrCode", label: "QRコード", Icon: QrCode },
  { name: "Fingerprint", label: "指紋", Icon: Fingerprint },
  { name: "Footprints", label: "足跡", Icon: Footprints },
  { name: "Hand", label: "ハンド", Icon: Hand },
];

const ICON_MAP = {};
for (const entry of ICON_CATALOG) {
  ICON_MAP[entry.name] = entry.Icon;
}

export function resolveIcon(name) {
  if (!name) return null;
  return ICON_MAP[name] || null;
}